### ISSUE TITLE
Helmholtz equation results

### ISSUE THREAD

**Issue by CamiVasz** [Ferrite-FEM/Ferrite.jl#288]
I was trying to replicate the solution for the Helmholtz equation given in https://github.com/KristofferC/JuAFEM.jl/blob/master/docs/src/literate/helmholtz.jl
and I am having troubles with the visualization of the output, is there another way to do it rather than installing a visualizer for .vtu files?

**Comment by fredrikekre** [comment]
What visualizer did you use? The example works for me when visualizing the .vtu file in ParaView.

**Comment by bocc** [comment]
If you want a Julia-only solution, you can try Makie. This is not perfect (as quads are shown as triangles), but perhaps someone will correct me. So assuming you've run the example:

```julia
using Makie

connectivity = vcat(collect.(getfield.(grid.cells,:nodes))'...)

nodes = vcat(collect.(getfield.(getfield.(grid.nodes,:x),:data))'...)

scene = Makie.mesh(nodes, connectivity, color = u, shading = false)
```

ParaView can seem complicated at first, but it does work. You need to press the green 'Apply' button after loading your file, and then you can choose Coloring to be `u` instead of a solid color.

**Comment by KristofferC** [comment]
Don't think there is much to do here.
