### ISSUE TITLE
Naming convention for getters

### ISSUE THREAD

**Issue by KnutAM** [Ferrite-FEM/Ferrite.jl#741]
In #664 the question of consistent naming of (exported/documented) getters came up. In particular changing `get*` to `get_*`, changes a lot of functions. Changing some of these would be very breaking (but should also be ok by leaving as deprecated) for user code, but here is just a list of the different getters we have exported, to facilitate the discussion.  

# Already following the convention
```julia 
get_rhs_data,
get_point_values
get_grid # #655 
get_*dim # #655
get_cell_coordinates # #664 
get_cell_coordinates! # #664 
get_node_coordinate # #664 
```

# Exports not following the `get_*` convention
## `Interpolation`
```julia
getnbasefunctions
```

## `QuadratureRule`
```julia
getnquadpoints,
getweights,
getpoints,
```

## `FEValues`
```julia
shape_value,
shape_gradient,
shape_symmetric_gradient,
shape_divergence,
shape_curl,
function_value,
function_gradient,
function_symmetric_gradient,
function_divergence,
function_curl,
spatial_coordinate,
getnormal,
getdetJdV,
```

## `AbstractGrid`
```julia
getneighborhood,
faceskeleton,
getcells,
getncells,
getnodes,
getnnodes,
getcelltype,
getcellset,
getnodeset,
getfaceset,
getedgeset,
getvertexset,
getcoordinates,  # Deprecated in #664
getcoordinates!, # Deprecated in #664
getcellsets,
getnodesets,
getfacesets,
getedgesets,
getvertexsets,
nfaces,
```

## `DofHandler`
```julia
ndofs,
ndofs_per_cell,
celldofs!,
celldofs,
dof_range,
```

## `CellCache`
```julia
cellid
```

**Comment by KnutAM** [comment]
My suggestion would be to be consistent in prepending `get`, but not enforcing the underscore if readable without (following the Base [convention](https://docs.julialang.org/en/v1/manual/style-guide/#Use-naming-conventions-consistent-with-Julia-base/)). The exception would be `FEValues`

With this, the following changes could be made
```julia
faceskeleton -> get_face_skeleton
ndofs -> getndofs # compare with e.g. getncells
ndofs_per_cell -> get_num_celldofs # Note sure what is best here
celldofs! -> get_cell_dofs!
celldofs -> get_cell_dofs
cellid -> get_cell_id
dof_range -> get_dof_range
```

`FEValues` are quite special, since most don't have `get` first, except `getnormal` and `getdetJdV`.
These are also frequently used in user code. Not sure what the best option here is, perhaps change these to `face_normal` and `detJdV` (or `quadrature_weight`).

**Comment by termi-official** [comment]
Note that `quadrature_weight` is something diferent than `detJdV`.

**Comment by KnutAM** [comment]
> Note that quadrature_weight is something diferent than detJdV.

True, it is confusing with `getweights(qr)` returning the weight for the reference cell and `quadrature_weight(cv, q_point)` returning the weight for the actual cell, didn't think very far. Striking out that suggestion!

**Comment by fredrikekre** [comment]
Some suggestions perhaps:
```
getnbasefunctions -> n_shape_functions

getnquadpoints    -> n_quad_points
getweights        -> remove from export
getpoints         -> remove from export

getnormal         -> face_normal
getdetJdV         -> detJdV

getcellsets       -> remove from export
getnodesets       -> remove from export
getfacesets       -> remove from export
getedgesets       -> remove from export


ndofs             -> n_dofs
ndofs_per_cell    _> n_dofs_per_cell
```

**Comment by KnutAM** [comment]
For me the `n_*` doesn't read to well, and to be consistent between grid and dofhandler, I would suggest these then
```julia
ndofs -> get_num_dofs
getncells -> get_num_cells
getnnodes -> get_num_nodes
ndofs_per_cell -> get_num_celldofs # as above
```

**Comment by termi-official** [comment]
Can you elaborate on
```
getcellsets       -> remove from export
getnodesets       -> remove from export
getfacesets       -> remove from export
getedgesets       -> remove from export
```
?

**Comment by fredrikekre** [comment]
What do you do with them? I didn't even knew they existed until now :)

**Comment by termi-official** [comment]
I sorry I misread. So we keep e.g. `getcellset` and remove `getcellsets`?

**Comment by kimauth** [comment]
Thanks for the comprehensive overview Knut!

I am however somewhat concerned to structurally break big parts of the commonly used API ("just") for renaming. Personally, these inconsistencies have never bothered me, even though I agree that if we were starting from scratch it would be nice to use consistent naming.

Here are some more detailed thoughts/concerns:
- Why do you want to introduce `get_*`, while it seems from the overview that in most places we use `get*` at the moment? The only function names that used `get_` until yesterday were `get_rhs_data` and `get_point_values` - both related to functionality that is rather recent and probably not that commonly used. Could it be an alternative to change these? 

- Most functions from the `FEValues` section are heavily used in element routines. Perhaps the readability of these will suffer from adding a lot of `get_`? Many of these functions also do computations instead of just doing a look-up, in which case prepending `get` seems a bit confusing to me. (Is that just me?)

- As pointed out above by Fredrik, some functions of the `Grid` block should maybe not be exported, e.g. the following are not used anywhere in the Examples: `faceskeleton, getnodes, getnnodes, getcelltype, getcellsets, getnodesets, getfacesets, getedgesets, getvertexsets`.

My main concern is that the resulting breaking changes might be very annoying compared to the gain that a more consistent API gives. Personally, I would be less worried about breaking changes that evolve from making the API more consistent with the least amount of breaking changes needed compared to a redesign.

**Comment by KnutAM** [comment]
Thanks for the feedback Kim - I think we agree on most points:

* That is why I [suggested ](https://github.com/Ferrite-FEM/Ferrite.jl/issues/741#issuecomment-1585620386) to **not** change `get*` to `get_*` (that stemmed from [this ](https://github.com/Ferrite-FEM/Ferrite.jl/pull/664#pullrequestreview-1473330260) comment, and I made this issue to give an overview of the implications, and the implication convinced me (and I think Fredrik too) that we should not change).  
* Absolutely agree with you! A thought was if `getdetJdV` and `getnormal` should be made consistent with other FEValues functions - but as you say, not to be taken lightly since at least `getdetJdV` is used a lot in user code.
* Exporting fewer things (those rarely used and not used in the examples) would be great!

**Comment by fredrikekre** [comment]
`getnbasefunctions` stands out a bit since we use `shape`, not `base`, for everything else(?).

**Comment by fredrikekre** [comment]
Me, @KristofferC, @lijas, and @kimauth discussed this a bit and we think things are mostly fine, and in particular not worth the extra churn. So since we are not planning to change any of the names here, perhaps we should revert #664 ? `get_node_coordinate` is fine to keep, but shouldn't be exported (I don't think it is something you would ever use as a user).

The unused functions can/should be removed from the export list though.

**Comment by termi-official** [comment]
For the revert, what about `get_grid` and the other recently introduced functions?

**Comment by termi-official** [comment]
Yes. This was more about the naming convention, because we e.g. introduced the "_" with this issue in mind.
