### ISSUE TITLE
Refactoring of examples into tutorials, how-to guides, and code gallery.

### ISSUE THREAD

**Issue by KristofferC** [Ferrite-FEM/Ferrite.jl#745]
We have been talking a bit about a refactoring to how the examples are displayed.

As it is right now, we are kind of mixing real tutorials (like the heat equation) that teaches a user new concepts, extensions to tutorials that adds something to an existing tutorial (like threading or L2 project post processing) and also "random" FEM examples that are cool but are not really a tutorial nor an extension (like the Topology optimization example).

It night be good to spit this into three categories:

- Tutorials: these are pedagogical which aim to teach certain features of Ferrite itself
-  How to guides: these are shorter that aim to show an "extension" to a tutorial which typically involves something more advanced, like multithreading.
- Code gallery: These are random cool projects that someone that is interested in could find useful, like the topology optimization example.

**Comment by fredrikekre** [comment]
Here is a suggested partitioning:

- Tutorials:
  - *Heat equation*. New topics/focused on: Grid, DofHandler, CellValues, ConstraintHandler, Dirichlet, linear solve, exporting solution (does this one already cover too much?)
  - *Incompressible elasticity*: New topics/focused on: mixed finite elements (multiple fields), vector-valued field, Neumann boundary conditions
  - *Hyperelasticity*.  New topics/focused on: non-linear problem, AD for the material (although not directly a Ferrite topic)
  - *von Mises plasticity*: non-linear problem with state variables etc
  - *Time dependent problem*: time integration
  - *Computational homogenization*: periodic BC, reading a Gmsh mesh from file
  - *Stokes flow*: mesh generation with Gmsh, more advanced periodic constraint, affine constraint for mean value constraint
 - *Navier Stokes*: advanced usage but doesn't really introduce much new? (Well, DiffEq usage, but I think we should have a simpler How-to with that (e.g. heat equation). Could be an advanced tutorial I think.
  - *Linear shell*: shows how one can "hack" around with Ferrite for custom things
- How to:
  - *Postprocessing*: evaluation in arbitrary points, L2 projection of quadrature data
  - *Multithreading*: multithreaded assembly, coloring
- Gallery
 - *Nearly incompressible hyperelasticity*: basically just combination of two of the tutorials, doesn't really present something new
 - *Topology optimization*: Also cool, but doesn't really introduce new Ferrite concepts (?)
 - *Ginzburg-Landau*: same as above

Some things that I think we should add: 
 - How-to use OrdinaryDiffEq for time integration (extension of heat equation?)
 - How-to use ForwardDiff.jl for the element routine (could also be an extension of the heat equation)
 - How-to select the linear solver (not much of a how-to, but nice to have a section on this since we use `\` for almost all examples).

**Comment by termi-official** [comment]
Quickly answering `How-to use OrdinaryDiffEq for time integration (extension of heat equation?)` - this one is still not 100% functional at this point, unfortunately.
