### ISSUE TITLE
A Loop over a CellIterator returns an Object of type CellCache

### ISSUE THREAD

**Issue by Firimo** [Ferrite-FEM/Ferrite.jl#775]
Hello,

The Minimal working example looks as follows

```
using Ferrite

grid = generate_grid(Quadrilateral, (5,5))

for cell in CellIterator(grid)
    @show typeof(cell)
    break
end
```

where `cell` is of the type`CellCache`. However, I would expect `cell` to be of the type `CellIterator` and this used (v0.3.10) to be the standard behavior. 

What I am trying to say is, that the real issue is, that v0.3.11 should have been called v0.4.11, since it introduced a breaking change. 

Consequently there are two pathways, either the behavior of the `CellIterator` constructor is changed, or all Ferrite.jl versions dating back to v0.3.11 are renamed v0.4.xx. 

Kind regards

P.S.: I believe this issue arises from a function called `Base.iterate()` found in the file iterators.jl

**Comment by Firimo** [comment]
Hi @fredrikekre ,

indeed I have read #546 and indeed I use `f(::CellIterator)`. Independent of my personal struggle with version maintenance, it does nonetheless seem rather counter-intuitive from a user perspective to construct a `CellIterator` and get a `CellCache` object.

Thanks for your (very) quick answer

**Comment by fredrikekre** [comment]
> it does nonetheless seem rather counter-intuitive from a user perspective to construct a CellIterator and get a CellCache object.

I disagree. One of the reasons for #546 was actually that the _previous_ behavior was counter-intuitive for many people. For example, if you loop over a vector, the iterates are not the vector itself, but the _elements_ of the vector. Similarly, after #546, the elements of the `CellIterator` are the `CellCaches`.

(Also, since you are a Ferrite user I haven't seen before: Welcome! We are hosting a user and developer day on October 6 in Bochum, Germany, and everyone curious about Ferrite is welcome to join, see https://ferrite-fem.github.io/FerriteCon/ for more details.)

**Comment by Firimo** [comment]
Hi @fredrikekre ,

That is, I have to say, a logic I cannot argue against and thanks for the welcoming words, they are receipted gratefully.

Greetings
