### ISSUE TITLE
Too tight tolerance for pyramid interpolation tests?

### ISSUE THREAD

**Issue by KnutAM** [Ferrite-FEM/Ferrite.jl#811]
Is this too tight tolerance for the test, or isn't the floating point error sufficiently low?
Leaving it here as a future todo, failed on Windows on this run: 
https://github.com/Ferrite-FEM/Ferrite.jl/actions/runs/6441434254/job/17491226328

```
Lagrange{RefPyramid, 2}(): Test Failed at D:\a\Ferrite.jl\Ferrite.jl\test\test_interpolations.jl:56
  Expression: sum([shape_value(interpolation, x, i) for i = 1:n_basefuncs]) ≈ 1.0
   Evaluated: 1.000000060768798 ≈ 1.0
```

**Comment by lijas** [comment]
I am guessing this happens when z is close to one, where there is a singularity for pyramids.

Looking at the code that tests this ([ `x = rand(Tensor{1, ref_dim}) `.)](https://github.com/Ferrite-FEM/Ferrite.jl/blob/e9ae940a3b6965d78bfd1ae03827e7584bfddac4/test/test_interpolations.jl#L52C33-L52C33), it seems like the generated point can be outside the parametric bounds for triangles, pyramids etc. Maybe we only generate points within the parametric bounds? I dont know if that will fix this issue however.

**Comment by KnutAM** [comment]
Nice! 
That sounds very reasonable to require!

I guess we could also add a printout of `x` so that we know that value in case it fails again?

**Comment by lijas** [comment]
Sounds good. Is there a way to generate a point within a domain? I guess one could just generate a random point and check if it is inside the domain, but then the distrubtion of points will not be uniform in the domain I think.

**Comment by KnutAM** [comment]
I think all reference shapes are convex, so a random linear combination with coefficients in [0,1] should work. Something like 
```julia
x_ref = reference_coordinates(ip)
i = rand(1:length(x_ref))
x = rand(length(x_ref)) .* (x_ref .- (x_ref[i],)) / (length(x_ref)-1) + x_ref[i]`
```

**Comment by termi-official** [comment]
Btw, next time we hit tolerance issues we also might try out an automated expression optimization system like Herbie https://herbie.uwplse.org/doc/2.0/release-notes.html . I am not aware of a Julia equivalent.
